server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: classpath:application-discovery.yml
  cloud:
    consul:
      discovery:
        metadata:
          displayName: API Gateway Service
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/config-service/**
          filters:
            - RewritePath=/config-service/(?<path>.*), /$\{path}
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
